#!/usr/bin/env python3
"""
Generate OpenROAD TCL script to place macros.

This creates a simple TCL script that can be sourced in OpenROAD
to set macro positions from our placement algorithm.

Usage:
    python scripts/generate_macro_placement_tcl.py --benchmark ariane133
"""

import re
import sys
import argparse
import torch
from pathlib import Path

from macro_place.loader import load_benchmark_from_dir


def generate_random_placement(benchmark, seed=42):
    """Generate random placement for demo."""
    torch.manual_seed(seed)
    placement = torch.zeros(benchmark.num_macros, 2)

    for i in range(benchmark.num_macros):
        w, h = benchmark.macro_sizes[i]
        x_min, x_max = w / 2, benchmark.canvas_width - w / 2
        y_min, y_max = h / 2, benchmark.canvas_height - h / 2

        x = torch.rand(1) * (x_max - x_min) + x_min
        y = torch.rand(1) * (y_max - y_min) + y_min

        placement[i, 0] = x
        placement[i, 1] = y

    # Respect fixed macros
    fixed_mask = benchmark.macro_fixed
    if fixed_mask.any():
        placement[fixed_mask] = benchmark.macro_positions[fixed_mask]

    return placement


def write_openroad_placement_tcl(placement, benchmark, plc, output_file):
    """
    Write OpenROAD TCL script to place macros using place_macro command.

    Args:
        placement: [num_macros, 2] tensor of (x, y) positions in microns
        benchmark: Benchmark object
        plc: PlacementCost object
        output_file: Output TCL file path
    """
    with open(output_file, 'w') as f:
        f.write("# OpenROAD Macro Placement Script\n")
        f.write("# Generated by partcl-macro-place-challenge\n")
        f.write("#\n")
        f.write("# Usage: source this file after initialize_floorplan in OpenROAD\n")
        f.write("#\n\n")

        f.write("puts \"Placing macros...\"\n\n")

        # Convert to numpy for easier access
        placement_np = placement.cpu().numpy()

        # Place each macro using place_macro command
        placed_count = 0
        for i, macro_idx in enumerate(benchmark.hard_macro_indices):
            node = plc.modules_w_pins[macro_idx]
            instance_name = node.get_name()

            # Escape brackets for OpenROAD (e.g., "block[0]" -> "block\\[0\\]")
            instance_name_escaped = instance_name.replace('[', '\\[').replace(']', '\\]')

            x, y = placement_np[i]

            # Get macro size
            w = node.get_width()
            h = node.get_height()

            # place_macro uses lower-left corner, not center
            # So convert from center to lower-left
            x_ll = x - w / 2
            y_ll = y - h / 2

            # Get orientation
            orientation = node.get_orientation() if node.get_orientation() else "R0"

            f.write(f"# Placing {instance_name}\n")
            f.write(f"place_macro \\\n")
            f.write(f"    -macro_name {{{instance_name_escaped}}} \\\n")
            f.write(f"    -location {{{x_ll:.6f} {y_ll:.6f}}} \\\n")
            f.write(f"    -orientation {orientation}\n\n")

            placed_count += 1

        f.write(f"puts \"Placed {placed_count} macros\"\n")

    print(f"✓ Generated OpenROAD placement TCL: {output_file}")
    print(f"  Placed {placed_count} macros")


def _plc_extract_group_and_index(plc_name):
    """Extract sram group prefix and flat macro index from a .plc name.

    .plc format: i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[K].i_ram
    Returns: (group_prefix_in_odb_format, K)

    The group prefix is everything before 'macro_mem[K]', converted to ODB naming
    (brackets to underscores, '/' to '.').  K is the flat macro index within that group.
    """
    # Extract macro_mem index
    m = re.search(r'/macro_mem\[(\d+)\]\.i_ram$', plc_name)
    if not m:
        return None, None
    macro_idx = int(m.group(1))
    prefix = plc_name[:m.start()]

    # Convert prefix to ODB format: brackets -> underscores, '/' -> '.'
    prefix = re.sub(r'\[(\d+)\]\.', r'_\1__', prefix)
    prefix = re.sub(r'\[(\d+)\]$', r'_\1__', prefix)
    prefix = prefix.replace('/', '.')

    return prefix, macro_idx


def _write_generic_size_bucketed_tcl(size_buckets, output_file, total_macros):
    """Generic macro placement TCL: pair ODB macros with .plc positions by master size.

    Emits a TCL script that iterates every block instance in ODB, groups by
    (master_width, master_height) in DBU, then for each bucket assigns the
    pre-sorted list of .plc positions (sorted by x,y) in order.

    This reproduces the placement's geometric distribution per-master-type.
    It does NOT preserve the original plc-name → odb-name correspondence, so
    within a size bucket macros may swap identities. This is a valid
    OpenROAD baseline for the placement but not necessarily identical timing.
    """
    with open(output_file, 'w') as f:
        f.write("# Macro Placement for OpenROAD-flow-scripts (generic size-bucketed)\n")
        f.write("# Pairs ODB macros with .plc positions by (master_width, master_height).\n\n")

        # Emit per-bucket position lists sorted by (x, y)
        f.write("set _buckets [dict create]\n")
        for key in sorted(size_buckets.keys()):
            w_dbu100, h_dbu100 = key
            entries = sorted(size_buckets[key], key=lambda e: (e[0], e[1]))
            # key: "W_H" where both are in DBU*100 (um * 100 * 1 = nm*10, but DBU for nangate45 is 2000/um)
            bucket_id = f"{w_dbu100}_{h_dbu100}"
            f.write(f'# bucket {bucket_id}: {len(entries)} macros, master ~{w_dbu100/100.0}um x {h_dbu100/100.0}um\n')
            f.write(f'dict set _buckets "{bucket_id}" [list \\\n')
            for (x_ll, y_ll, orient, plc_name) in entries:
                f.write(f'    [list {x_ll:.6f} {y_ll:.6f} {orient} "{plc_name}"] \\\n')
            f.write("]\n")
        f.write("\n")

        f.write("""# Walk every block instance, pair it with the next position from its size bucket.
set _placed 0
set _unmatched [list]
set _cursor [dict create]
set block [ord::get_db_block]
# Group ODB instances by size bucket, sort by instance name for determinism.
set _odb_by_bucket [dict create]
foreach inst [$block getInsts] {
    if {![$inst isBlock]} { continue }
    set master [$inst getMaster]
    set mw [$master getWidth]
    set mh [$master getHeight]
    # Convert DBU to um*100 (DBU-per-um from ORD is usually 2000 for nangate45)
    set dbu [[ord::get_db_tech] getDbUnitsPerMicron]
    set w100 [expr {round(double($mw) / $dbu * 100.0)}]
    set h100 [expr {round(double($mh) / $dbu * 100.0)}]
    set bid "${w100}_${h100}"
    dict lappend _odb_by_bucket $bid [$inst getName]
}

dict for {bid odb_names} $_odb_by_bucket {
    # Sort ODB names so the cursor order is deterministic (numeric-aware).
    set sorted_names [lsort -dictionary $odb_names]
    set positions [expr {[dict exists $_buckets $bid] ? [dict get $_buckets $bid] : [list]}]
    set n_pos [llength $positions]
    set n_odb [llength $sorted_names]
    if {$n_pos != $n_odb} {
        puts "WARNING: bucket $bid size mismatch: $n_odb ODB instances vs $n_pos .plc positions"
    }
    set i 0
    foreach name $sorted_names {
        if {$i >= $n_pos} {
            lappend _unmatched "$name (bucket=$bid, no position)"
            incr i
            continue
        }
        lassign [lindex $positions $i] x y orient plc_name
        place_macro -macro_name [list $name] -location [list $x $y] -orientation $orient
        incr _placed
        incr i
    }
}

""")
        f.write(f'puts "Placed $_placed macros (expected {total_macros})"\n')
        f.write('if {[llength $_unmatched] > 0} {\n')
        f.write('    puts "Unmatched ODB instances:"\n')
        f.write('    foreach u $_unmatched { puts "  $u" }\n')
        f.write('}\n')
    print(f"✓ Generated generic ORFS macro placement TCL: {output_file}")
    print(f"  {total_macros} macros across {len(size_buckets)} size buckets")


def write_orfs_macro_placement(placement, benchmark, plc, output_file, core_area=None):
    """
    Write macro placement in ORFS format using place_macro command.

    Tries the ariane-style name-matched placement first; if any macro name
    doesn't match the `.../macro_mem[K].i_ram` pattern, falls back to a
    generic (width, height)-bucket matcher that pairs .plc macros with ODB
    instances by master size. Within a bucket, .plc entries are sorted by
    (x, y) so the pairing is deterministic.

    Args:
        placement: [num_macros, 2] tensor of (x, y) positions in microns
        benchmark: Benchmark object
        plc: PlacementCost object
        output_file: Output TCL file path
        core_area: Optional tuple (x_min, y_min, x_max, y_max) to clamp positions
    """
    from collections import defaultdict

    placement_np = placement.cpu().numpy()

    # Build placement data keyed by (group_prefix, flat_macro_index)
    group_data = defaultdict(dict)  # group_prefix -> {K: (x, y, orient, plc_name)}
    # Also collect a generic bucketed list for the fallback path
    size_buckets = defaultdict(list)  # (w_um_100, h_um_100) -> [(x, y, orient, plc_name)]
    total_macros = 0
    unparseable = 0

    for i, macro_idx in enumerate(benchmark.hard_macro_indices):
        node = plc.modules_w_pins[macro_idx]
        plc_name = node.get_name()
        x, y = placement_np[i]
        w = node.get_width()
        h = node.get_height()
        x_ll = x - w / 2
        y_ll = y - h / 2

        if core_area is not None:
            margin = 2.0
            core_x_min, core_y_min, core_x_max, core_y_max = core_area
            x_ll = max(core_x_min + margin, min(x_ll, core_x_max - w - margin))
            y_ll = max(core_y_min + margin, min(y_ll, core_y_max - h - margin))

        orientation = node.get_orientation() if node.get_orientation() else "R0"
        # Always populate the size-bucket list (used by the generic fallback)
        bucket_key = (round(w * 100), round(h * 100))
        size_buckets[bucket_key].append((float(x_ll), float(y_ll), orientation, plc_name))

        group_prefix, macro_k = _plc_extract_group_and_index(plc_name)

        if group_prefix is not None:
            group_data[group_prefix][macro_k] = (x_ll, y_ll, orientation, plc_name)
            total_macros += 1
        else:
            unparseable += 1
    # If any name was unparseable, switch to the generic size-bucketed path
    if unparseable > 0:
        total_macros = sum(len(v) for v in size_buckets.values())
        print(f"  Using generic size-bucketed matcher ({unparseable} names did not match ariane pattern)")
        return _write_generic_size_bucketed_tcl(size_buckets, output_file, total_macros)
    # else: fall through to the ariane-style TCL below

    with open(output_file, 'w') as f:
        f.write("# Macro Placement for OpenROAD-flow-scripts\n")
        f.write("# Generated by partcl-macro-place-challenge\n")
        f.write("#\n")
        f.write("# Two-pass runtime matching: groups ODB macros by sram block prefix,\n")
        f.write("# then matches to .plc macro_mem[K] by linear index within each group.\n\n")

        # Emit placement data: dict of group_prefix -> dict of flat_index -> {x y orient}
        f.write("# Placement data: group_prefix -> flat_index -> {x y orient plc_name}\n")
        f.write("set _gpd [dict create]\n")
        for group_prefix in sorted(group_data.keys()):
            for k in sorted(group_data[group_prefix].keys()):
                x_ll, y_ll, orient, plc_name = group_data[group_prefix][k]
                f.write(f'dict set _gpd "{group_prefix}" {k} [list {x_ll:.6f} {y_ll:.6f} {orient} "{plc_name}"]\n')
        f.write("\n")

        # TCL matching logic
        f.write("""# Pass 1: Collect all block instances, grouped by sram prefix
# ODB name pattern: PREFIX.genblk1_G__i_ram.macro_mem_M
# We extract PREFIX (everything before .genblk1_), G, and M.
set _odb_groups [dict create]
set block [ord::get_db_block]
foreach inst [$block getInsts] {
    if {[$inst isBlock]} {
        set name [$inst getName]
        # Match the genblk pattern
        if {[regexp {^(.+)\\.genblk1_(\d+)__i_ram\\.macro_mem_(\d+)$} $name -> prefix genblk_idx mem_idx]} {
            dict lappend _odb_groups $prefix [list $genblk_idx $mem_idx $name]
        }
    }
}

# Pass 2: For each group, sort by (genblk_idx, mem_idx) to get linear ordering,
# then match to our .plc flat indices.
set _placed 0
set _unmatched_odb [list]
set _unmatched_plc [list]

dict for {prefix entries} $_odb_groups {
    # Sort entries by genblk_idx then mem_idx (both numeric)
    set sorted_entries [lsort -command {apply {{a b} {
        lassign $a ga ma
        lassign $b gb mb
        set ga [expr {int($ga)}]; set ma [expr {int($ma)}]
        set gb [expr {int($gb)}]; set mb [expr {int($mb)}]
        if {$ga != $gb} { return [expr {$ga - $gb}] }
        return [expr {$ma - $mb}]
    }}} $entries]

    # Assign linear index K=0,1,2,...
    set k 0
    foreach entry $sorted_entries {
        lassign $entry genblk_idx mem_idx odb_name
        if {[dict exists $_gpd $prefix] && [dict exists [dict get $_gpd $prefix] $k]} {
            lassign [dict get [dict get $_gpd $prefix] $k] x y orient plc_name
            place_macro -macro_name [list $odb_name] -location [list $x $y] -orientation $orient
            incr _placed
        } else {
            lappend _unmatched_odb "$odb_name (group=$prefix, k=$k)"
        }
        incr k
    }
}

""")
        f.write(f'puts "Placed $_placed macros (expected {total_macros})"\n')
        f.write(f'if {{$_placed != {total_macros}}} {{\n')
        f.write(f'    puts "WARNING: Expected {total_macros} macros but placed $_placed"\n')
        f.write('    if {[llength $_unmatched_odb] > 0} {\n')
        f.write('        puts "Unmatched ODB instances:"\n')
        f.write('        foreach u $_unmatched_odb { puts "  $u" }\n')
        f.write('    }\n')
        f.write("}\n")

    print(f"✓ Generated ORFS macro placement TCL: {output_file}")
    print(f"  {total_macros} macros across {len(group_data)} sram groups")


def main():
    parser = argparse.ArgumentParser(description='Generate OpenROAD macro placement TCL')
    parser.add_argument('--benchmark', default='ariane133',
                       help='Benchmark to use (default: ariane133)')
    parser.add_argument('--output', default='output/place_macros.tcl',
                       help='Output TCL file (default: output/place_macros.tcl)')
    parser.add_argument('--seed', type=int, default=42,
                       help='Random seed (default: 42)')

    args = parser.parse_args()

    # Create output directory
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("Generate OpenROAD Macro Placement TCL")
    print("=" * 80)
    print()

    # Load benchmark
    print(f"Loading benchmark: {args.benchmark}...")
    flows_dir = Path("external/MacroPlacement/Flows/NanGate45")
    benchmark_path = flows_dir / args.benchmark / "netlist" / "output_CT_Grouping"

    if not benchmark_path.exists():
        testcases_dir = Path("external/MacroPlacement/Testcases/ICCAD04")
        benchmark_path = testcases_dir / args.benchmark
        if not benchmark_path.exists():
            print(f"ERROR: Benchmark not found: {args.benchmark}")
            return 1

    benchmark, plc = load_benchmark_from_dir(str(benchmark_path))
    print(f"  ✓ Loaded {benchmark.name} ({benchmark.num_macros} macros)")
    print()

    # Generate placement (you would replace this with your algorithm)
    print(f"Generating random placement (seed={args.seed})...")
    placement = generate_random_placement(benchmark, seed=args.seed)
    print(f"  ✓ Generated placement")
    print()

    # Write TCL script
    print(f"Writing OpenROAD TCL script...")
    write_openroad_placement_tcl(placement, benchmark, plc, str(output_path))
    print()

    print("=" * 80)
    print("USAGE")
    print("=" * 80)
    print()
    print("In your OpenROAD flow, after loading LEF/netlist:")
    print()
    print(f"  source {args.output}")
    print()
    print("This will place all macros at the computed positions.")
    print("=" * 80)

    return 0


if __name__ == "__main__":
    sys.exit(main())
